# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Sam Doidge
tagline:          Coffee's for closers only.
url:              samdoidge.github.io/samdoidge.github.io
paginate:         1
baseurl:          /
author:
  name:           Sam Doidge	
  url:            http://samdoidge.com
  email:          sam@samdoidge.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/samdoidge/samdoidge.github.io
disqusid:			  samdoidge

# Custom header pages
pages_list:       
  About: '/about'
  Archive: '/archive'
