# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        "/:title"

# Setup
title:            Sam Doidge
tagline:          Coffee's for closers only.
url:              http://samdoidge.com
paginate:         5
baseurl:          http://samdoidge.com
author:
  name:           Sam Doidge	
  url:            http://samdoidge.com
  email:          sam@samdoidge.com

# Gems
gems:
  - jekyll-sitemap

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/samdoidge/samdoidge.github.io
disqusid:			  samdoidge

# Custom header pages
pages_list:       
  About: '/about'
  Archive: '/archive'
